[package]
name = "calculation_game"
version = "0.1.0"
authors = ["bqoul"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
rand = "*"
